

enum SpriteTags
{
    PAUSE_BUTTON_TAG = 1,
    MUTE_BUTTON_TAG,
    
	LEFT_BUTTON_TAG,
	RIGHT_BUTTON_TAG,
	
	CHANGE_WEAPON_BUTTON_TAG,
	ATTACK_BUTTON_TAG,
	JUMP_BUTTON_TAG,
	
	BACK_SPRITE_TAG,
	CLOUD_SPRITE_TAG,
    
    HITPOINT_TAG,
    HITPOINT_END_TAG = HITPOINT_TAG + 100,
    
};