#ifndef LittlePoo_timings_h
#define LittlePoo_timings_h

// Single button press loop iteration
#define MAXIMUM_FPS_RATE 60
//#define MAXIMUM_FPS_RATE 8

#define REPLICATOR_SINGLE_ITERATION (1.0 / MAXIMUM_FPS_RATE)

#define STAGE_TRANSITION_DURATION 1.2f
#define DEATH_TRANSITION_DURATION 0.01f

#ifdef TEST_RUN
    #define SINGLE_QUANTUM (0.046f)
#else
    #define SINGLE_QUANTUM (0.046f)
#endif
 
#define SINGLE_CHAR_RUNNING_TIME (0.1f)

#define COLLECT_OBJECT_MOVE_TIME (SINGLE_QUANTUM * 5)
#define SATELLITE_FALL_TIME (SINGLE_QUANTUM * 20)

// for debugging purps.
//#define SINGLE_QUANTUM 0.00f

// per single block! i.e. 32 pixels...
#define SINGLE_BLOCK_JUMP_TIMING (SINGLE_QUANTUM)
// slower
#define SINGLE_BLOCK_MOVE_TIMING (SINGLE_QUANTUM * 2)

////// ANIMATIONS:
#define WALK_ANIMATION_NEXT_FRAME_TIME (SINGLE_BLOCK_MOVE_TIMING)
#define IDLE_ANIMATION_NEXT_FRAME_TIME (2 * SINGLE_BLOCK_MOVE_TIMING)
#define TALK_ANIMATION_NEXT_FRAME_TIME (SINGLE_BLOCK_MOVE_TIMING)

#define INITIAL_DIALOGUE_WAIT_TIME (1.5f)
#define SHOW_DIALOGUE_PHRASE_TIME (3.0f)
#define DIALOGUE_FADE_IN_TIMING   (3.5f)

////// STAGES:
#define STAGE0_TIME_SECONDS 40
#define STAGE1_TIME_SECONDS 35
#define STAGE2_TIME_SECONDS 35
#define STAGE3_TIME_SECONDS 90
#define STAGE4_TIME_SECONDS 120
#define STAGE5_TIME_SECONDS 120
#define STAGE6_TIME_SECONDS 80

#endif
